<div id="header">
	<div class="wrap">
      <div id="navigation" class="menu">
        <?php if (!empty($primary_links)){ print theme('links', $primary_links, array('id' => 'primary', 'class' => 'links main-menu')); } ?>
      </div>
   		<a href="<?php print $front_page; ?>" title="Cascade Hardwood Group Home Page" rel="home" id="logo"><img src="<?php print $logo; ?>" alt="Cascade Hardwood Group Logo"/></a>
	</div>
	<div class="shadow">
		<div class="s1"></div>
		<div class="s2"></div>
	</div>
</div>
<div id="grade-selector-link">
	<div class="wrap">
   <a id="badge" href="/products"><span class="badge-white">Try the all new</span><span class="badge-black">Cascade Grade Selector&trade;</span></a>
	</div>
</div>
<div id="footer">
	<div class="wrap">
	<div id="footer-left">
	<ul>
		<li class="first">
			<a href="/lumber-sales">Lumber Sales</a>
		</li>
		<li class="">
			<a href="/products">Grade Selector</a>
		</li>
		<li>
			<a href="/log-procurement">Log Procurement</a>
		</li>
		<!-- <li>
			<a href="#">Pallet Stock</a>
		</li> -->
	</ul>
	<ul>
		<li class="first">
			<a href="/our-mills">Our Mills</a>
		</li>
		<li>
			<a href="/our-mills/cascade-hardwood">Cascade Hardwood</a>
		</li>
		<li>
			<a href="/our-mills/port-angeles-hardwood">Port Angeles Hardwood</a>
		</li>
	</ul>	
	<ul>
		<li class="first">
			<a href="/our-resources">Our Resources</a>
		</li>
		<li>
			<a href="/our-resources">Alder</a>
		</li>
		<li>
			<a href="/our-resources/maple">Maple</a>
		</li>
		<li>
			<a href="/our-resources/ash">Ash</a>
		</li>
	</ul>
	<ul>
		<li class="first">
			<a href="/contact-us">Contact Us</a>
		</li>
	</ul>
	</div>
	
	<div id="footer-right">
		<div id="questions">Question? Call <span>800-228-3065</span></div>
		<div id="made-in-the-usa"></div>
		<div id="footer-logos">
			<div id="footer-logo-cascade"></div>
			<div id="footer-logo-fsc"></div>
			<div id="footer-logo-nhla"></div>
		<div id="copyright">
			<span>&copy; Copyright 2011 Cascade Hardwood Group LLC. All rights reserved.</span>
		</div>
		</div>
		
	</div>
				
	</div>
	
</div>
